import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/shared/navbar/navbar'
import { Providers } from '@/redux/provider'
import Footer from './components/shared/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'pti-food-delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <section className="max-w-screen-lg mx-auto">
            <Navbar />
            {children}
          </section>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
