import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/shared/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'pti-food-delivery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className='max-w-screen-lg mx-auto'>
          <Navbar />
          {children}
        </section>
      </body>
    </html>
  );
}
